DROP DATABASE IF EXISTS HomeExtra2;
CREATE DATABASE HomeExtra2;
use HomeExtra2;
CREATE TABLE Home(
HomeID 			MEDIUMINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
HomeName		VARCHAR(50)		NOT NULL,
HomeCode		VARCHAR(5)		NOT NULL,
ModifiedDate	DATETIME DEFAULT NOW()
);
INSERT INTO Home(HomeID, HomeName, HomeCode, ModifiedDate)
VALUES 			(3, 'ABC', '2AKS5', now());
SELECT * FROM Home;